Встроенный в мозг радар
ThetaStation/ThetaStation pull request #148
Opened 2023-04-28 14:22 UTC by KIBORG04

## Описание PR

![image](https://user-images.githubusercontent.com/26389417/235173564-7e0285cb-cde3-45f1-aae0-f7f5351bddee.png)

**Скриншоты**

## Почему и что этот ПР улучшит
Та самая замена покет радару, которая облегчит возможность человеческого налёта на корабль врага. 

fix https://github.com/ThetaStation/ThetaStation/issues/140

2023-04-28 14:24 UTC, KIBORG04 commented on Content.Client/UserInterface/Systems/Radar/RadarUIController.cs
> +        SubscribeLocalEvent<RadarHudComponentAdded>(OnRadarHudAdded);
Если честно, вот эти ивенты не тестил, но поидее, они только для нашего клиента, а не всех вокруг

2023-04-28 14:27 UTC, KIBORG04 commented
Казалось бы, такая простая фича, но как я умер ее кодировать

2023-04-28 14:38 UTC, IlinMihail commented on Content.Client/UserInterface/Systems/Radar/Controls/SimpleRadar.cs
> +    // new because pendoses has hardcoded all size-related parameters
зачем быть токсиком + хев а не хез

2023-04-28 14:41 UTC, IlinMihail commented on Content.Client/UserInterface/Systems/Radar/Controls/SimpleRadar.cs
> +    {
ужасная копипаста, неужели мы не можем взять уже готовый радар контрол

2023-04-28 14:43 UTC, IlinMihail commented on Content.Shared/Theta/RadarHUD/RadarHUDSystem.cs
> +[ByRefEvent]
а смысл эти ивенты делать бай реф, мы же просто передаём значение в одну сторону, не?

2023-04-28 14:46 UTC, IlinMihail commented on Content.Shared/Theta/RadarHUD/RadarHUDSystem.cs
> +        RaiseLocalEvent(uid, ref ev);
ты уверен что ивенты стартапа компонентов не передаются на клиент тоже? и стартап может (хотя в данном случае наверное нет, но тем не менее) несколько раз вызываться за лайфтайм компонента, лучше юзать ивент на инит

2023-04-28 14:50 UTC, IlinMihail commented on Content.Shared/Theta/RadarHUD/RadarHUDSystem.cs
> +        RaiseLocalEvent(uid, ref ev);
и если не реплицируются, то почему ты в коде радар-уи контроллера подписываешся на локальный ивент (который во втором случае никогда там не появится)

2023-04-28 14:52 UTC, IlinMihail requested changes
жирная копипаста и немного странные ивенты, если я не прав то объясни пж

2023-04-28 16:40 UTC, LudwigVonChesterfield commented on Content.Client/UserInterface/Systems/Radar/Controls/SimpleRadar.cs
> +    // new because pendoses has hardcoded all size-related parameters
```suggestion
    // new because western collegues have hardcoded all size-related parameters
```

2023-04-28 16:41 UTC, LudwigVonChesterfield commented on Content.Client/UserInterface/Systems/Radar/Controls/SimpleRadar.cs
> +    {
в теории эти два радара же могут рисовать разные вещи, просто пока-что рисуют абсолютно точно то же... думаю копипаста оправдана

2023-04-28 16:42 UTC, LudwigVonChesterfield commented on Content.Client/UserInterface/Systems/Radar/RadarUIController.cs
> +        RadarGui.Visible = EntityManager.HasComponent<RadarHUDComponent>(_playerManager.LocalPlayer?.ControlledEntity);
можно кнопочку выключения хада как-то сделать?

2023-04-28 16:44 UTC, KIBORG04 commented on Content.Client/UserInterface/Systems/Radar/RadarUIController.cs
> +        RadarGui.Visible = EntityManager.HasComponent<RadarHUDComponent>(_playerManager.LocalPlayer?.ControlledEntity);
Можно, но зач

2023-04-28 16:45 UTC, KIBORG04 commented on Content.Client/UserInterface/Systems/Radar/Controls/SimpleRadar.cs
> +    {
В дискорде писал, копипаста бай дейзигн

2023-04-28 16:45 UTC, KIBORG04 commented on Content.Shared/Theta/RadarHUD/RadarHUDSystem.cs
> +[ByRefEvent]
Ээээ, я хз, но структура, как ивент. вроде круче, чем класс, как ивент

2023-04-28 16:46 UTC, KIBORG04 commented on Content.Shared/Theta/RadarHUD/RadarHUDSystem.cs
> +        RaiseLocalEvent(uid, ref ev);
Реплецируется, я не хочу на стороне контроллера это хендлить.

2023-04-28 16:58 UTC, KIBORG04 commented on Content.Client/UserInterface/Systems/Radar/Controls/SimpleRadar.cs
> +    // new because pendoses has hardcoded all size-related parameters
ЛИШЬ БЫ НЕ ДЕХАБ ЗА ЭТО

2023-04-28 17:00 UTC, ilinm1 commented on Content.Shared/Theta/RadarHUD/RadarHUDSystem.cs
> +[ByRefEvent]
я про бай реф а не стракт или класс. стракт реально лучше, но аннотация здесь не нужна

2023-04-28 17:04 UTC, KIBORG04 commented on Content.Shared/Theta/RadarHUD/RadarHUDSystem.cs
> +[ByRefEvent]
Она вроде обязательно для структур-ивентов

2023-04-28 17:11 UTC, IlinMihail commented on Content.Shared/Theta/RadarHUD/RadarHUDSystem.cs
> +[ByRefEvent]
да, я неправ

2023-04-28 17:12 UTC, IlinMihail commented on Content.Client/UserInterface/Systems/Radar/RadarUIController.cs
> +        RadarGui.Visible = EntityManager.HasComponent<RadarHUDComponent>(_playerManager.LocalPlayer?.ControlledEntity);
если плееру надоест окошко на 4 часть экрана

2023-04-28 17:15 UTC, KIBORG04 commented on Content.Client/UserInterface/Systems/Radar/RadarUIController.cs
> +        RadarGui.Visible = EntityManager.HasComponent<RadarHUDComponent>(_playerManager.LocalPlayer?.ControlledEntity);
У меня на монике 16:9 вы сами видите какую часть экрана она закрывает. К тому же, у меня ее большая часть располагается поверх черной полосы, ограничивающей вижон. На мониторах другого размера соотношения радара будет так же динамически изменено.

2023-04-29 00:49 UTC, LudwigVonChesterfield commented on Content.Client/UserInterface/Systems/Radar/RadarUIController.cs
> +        RadarGui.Visible = EntityManager.HasComponent<RadarHUDComponent>(_playerManager.LocalPlayer?.ControlledEntity);
во время пиу пиу перестрелки мне эта карта не нужна а закрывает левый нижний угол

2023-04-29 00:49 UTC, LudwigVonChesterfield commented on Content.Client/UserInterface/Systems/Radar/RadarUIController.cs
> +        RadarGui.Visible = EntityManager.HasComponent<RadarHUDComponent>(_playerManager.LocalPlayer?.ControlledEntity);
(я кстати не уверен что понимаю почему это не предмет а прямо в моск...)

2023-04-29 11:19 UTC, KIBORG04 commented on Content.Client/UserInterface/Systems/Radar/RadarUIController.cs
> +        RadarGui.Visible = EntityManager.HasComponent<RadarHUDComponent>(_playerManager.LocalPlayer?.ControlledEntity);
Видева:
https://cdn.discordapp.com/attachments/983458219517149304/1101582930557534329/Content.Client_GFMuTqrJUI.mp4

А еще сам радар прозрачный для мышки и не пропускает все клики сквозь.

Почему в мозк? Ради казуальности, и чтобы новенькие игроки АХУЕЛИ от такой фичи

2023-04-29 11:23 UTC, merged