Удаление команд без активных игроков
ThetaStation/ThetaStation pull request #230
Opened 2023-07-04 21:55 UTC by IlinMihail

## Описание PR
команды без активных игроков (с подключенными клиентами) автоматически удаляются
добавил команду для удаления команд (педалям)
убрал немного тупого кода из системы тим

**Скриншоты**

## Почему и что этот ПР улучшит

## Чеинжлог
:cl: ThetaStation
add: Команда для удаления команд (админам) - se_remteam
add: Команда для доступа к интерфейсу лобби (не нужно больше телепортироваться в лобби чтоб сменить команду) - se_lobby
fix: Команды без активных игроков автоматически удаляются

2023-07-06 15:10 UTC, LudwigVonChesterfield commented
ээ... нужна какая-то задержка перед удалением а то если я вышел из игры и команда в виде моей коробочки удалилась это неправильно

2023-07-07 14:50 UTC, IlinMihail commented
бля

2023-07-07 14:53 UTC, LudwigVonChesterfield commented on Content.Server/Theta/ShipEvent/Systems/ShipEventFactionSystem.cs
> +            if (team.ActiveMembers.Count == 0)
если цикл выше был бы по копии списка можно было бы команду удалять прямо здесь

2023-07-07 14:54 UTC, LudwigVonChesterfield requested changes
я не понимаю когда конкретно сейчас удаляются команды и не могу с чистой совестью это мержить пока не пойму

команда из одного человека (коробка)
чел вылетел из игры
его команда удаляется?

команда из одного человека (коробка)
чел вылетел из игры
чела убили
его команда удаляется?

2023-07-07 15:07 UTC, LudwigVonChesterfield approved these changes

2023-07-08 10:47 UTC, KIBORG04 commented on Content.Server/Theta/ShipEvent/RemoveTeamCommand.cs
> +    public string Help => "First arg - team name, second arg (optional) - removal reason";
А насколько сложно будет добавить автокомплит для названия команд?

2023-07-08 10:48 UTC, KIBORG04 commented on Content.Server/Theta/ShipEvent/RemoveTeamCommand.cs
> +            if (team.Name == args[0])
У нас же можно писать название команды через пробел. Не будет ли прикола, если тиму "БЕЛЫЕ НАТУРАЛЫ АБОБА" нельзя будет кикнуть как раз из-за того, что она распаршивается в 3 аргумента?

2023-07-08 10:49 UTC, KIBORG04 commented on Content.Server/Theta/ShipEvent/RemoveTeamCommand.cs
> +            if (team.Name == args[0])
То же и про ризон, если он из нескольких слов

2023-07-08 12:49 UTC, IlinMihail commented
ну я мержу

2023-07-08 12:49 UTC, merged