Reset all fields in ship system
ThetaStation/ThetaStation pull request #239
Opened 2023-07-08 18:13 UTC by KIBORG04

## Описание PR
Надеюсь, фикс всех проблем

**Скриншоты**

## Почему и что этот ПР улучшит

## Чеинжлог

2023-07-08 18:24 UTC, IlinMihail requested changes
я понимаю что легче просто всё сбрасывать нахуй, но большинство из этих полей задаются на раундстарте из конфига. стоит сбрасывать таймеры, списки прототипов и подобное, но не кол-во спавна лутбоксов например. так короче и понятнее.

2023-07-08 22:50 UTC, KIBORG04 commented
> я понимаю что легче просто всё сбрасывать нахуй, но большинство из этих полей задаются на раундстарте из конфига. стоит сбрасывать таймеры, списки прототипов и подобное, но не кол-во спавна лутбоксов например. так короче и понятнее

Там по моему все равно все перезаписывается в итоге

2023-07-09 14:47 UTC, IlinMihail commented
лан пох, надеюсь ты потом поменяешь

2023-07-09 14:47 UTC, merged

2023-07-09 14:48 UTC, KIBORG04 commented
> лан пох, надеюсь ты потом поменяешь

Я думаю, тебе самому будет теперь легче. Или напиши че убрать, я просто не хочу лезть, а ты уже знаешь